/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/special-operations/health/sum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate sum of health values for all Space Marines */
        get: operations["calculateHealthSum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-operations/health/average": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate average health value for all Space Marines */
        get: operations["calculateHealthAverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-operations/space-marines/filter-by-weapons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter Space Marines by weapon types with pagination */
        get: operations["filterSpaceMarinesByWeapons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-operations/chapters/{chapterId}/assign-marine/{marineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign a Space Marine to a Chapter */
        put: operations["assignMarineToChapter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-marines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Space Marines (paginated) */
        get: operations["getAllSpaceMarines"];
        put?: never;
        /** Create a new Space Marine */
        post: operations["createSpaceMarine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-marines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Space Marine by ID */
        get: operations["getSpaceMarineById"];
        /** Update a Space Marine by ID */
        put: operations["updateSpaceMarine"];
        post?: never;
        /** Delete a Space Marine by ID */
        delete: operations["deleteSpaceMarine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-marines/health/sum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate sum of health values for all Space Marines
         * @deprecated
         * @description This endpoint is deprecated. Use /special-operations/health/sum instead.
         */
        get: operations["calculateHealthSumLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-marines/health/average": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate average health value for all Space Marines
         * @deprecated
         * @description This endpoint is deprecated. Use /special-operations/health/average instead.
         */
        get: operations["calculateHealthAverageLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordinates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Coordinates (paginated) */
        get: operations["getAllCoordinates"];
        put?: never;
        /** Create new Coordinates */
        post: operations["createCoordinates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordinates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coordinates by ID */
        get: operations["getCoordinatesById"];
        /** Update Coordinates by ID */
        put: operations["updateCoordinates"];
        post?: never;
        /** Delete Coordinates by ID */
        delete: operations["deleteCoordinates"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Chapters (paginated) */
        get: operations["getAllChapters"];
        put?: never;
        /** Create a new Chapter */
        post: operations["createChapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Chapter by ID */
        get: operations["getChapterById"];
        /** Update a Chapter by ID */
        put: operations["updateChapter"];
        post?: never;
        /** Delete a Chapter by ID */
        delete: operations["deleteChapter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedSpaceMarineResponse: {
            content: components["schemas"]["SpaceMarine"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PaginatedCoordinatesResponse: {
            content: components["schemas"]["CoordinatesWithId"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PaginatedChapterResponse: {
            content: components["schemas"]["ChapterWithId"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        SpaceMarine: {
            /**
             * Format: int32
             * @description Unique auto-generated ID (> 0)
             */
            id: number;
            /** @description Non-empty, non-null name */
            name: string;
            /**
             * Format: int64
             * @description ID of associated Coordinates
             */
            coordinatesId: number;
            /**
             * Format: date-time
             * @description Auto-generated creation timestamp
             */
            creationDate: string;
            /**
             * Format: int64
             * @description ID of associated Chapter
             */
            chapterId: number;
            /**
             * Format: int64
             * @description Health must be > 0
             */
            health: number;
            loyal?: boolean | null;
            /**
             * @description Astartes category
             * @enum {string|null}
             */
            category?: "AGGRESSOR" | "INCEPTOR" | "TACTICAL" | "CHAPLAIN" | "APOTHECARY" | null;
            /**
             * @description Type of weapon used by the Space Marine
             * @enum {string}
             */
            weaponType: "BOLTGUN" | "HEAVY_BOLTGUN" | "FLAMER" | "HEAVY_FLAMER" | "MULTI_MELTA";
        };
        SpaceMarineCreateRequest: {
            name: string;
            /** Format: int64 */
            coordinatesId: number;
            /** Format: int64 */
            chapterId: number;
            /** Format: int64 */
            health: number;
            loyal?: boolean | null;
            /** @enum {string|null} */
            category?: "AGGRESSOR" | "INCEPTOR" | "TACTICAL" | "CHAPLAIN" | "APOTHECARY" | null;
            /** @enum {string} */
            weaponType: "BOLTGUN" | "HEAVY_BOLTGUN" | "FLAMER" | "HEAVY_FLAMER" | "MULTI_MELTA";
        };
        SpaceMarineUpdateRequest: {
            name?: string;
            /** Format: int64 */
            coordinatesId?: number;
            /** Format: int64 */
            chapterId?: number;
            /** Format: int64 */
            health?: number;
            loyal?: boolean | null;
            /** @enum {string|null} */
            category?: "AGGRESSOR" | "INCEPTOR" | "TACTICAL" | "CHAPLAIN" | "APOTHECARY" | null;
            /** @enum {string} */
            weaponType?: "BOLTGUN" | "HEAVY_BOLTGUN" | "FLAMER" | "HEAVY_FLAMER" | "MULTI_MELTA";
        };
        Coordinates: {
            /**
             * Format: int64
             * @description X coordinate
             */
            x: number;
            /**
             * Format: float
             * @description Y coordinate (must be ≤ 343)
             */
            y: number;
        };
        CoordinatesWithId: components["schemas"]["Coordinates"] & {
            /**
             * Format: int64
             * @description Unique auto-generated ID
             */
            id: number;
        };
        Chapter: {
            /** @description Non-empty, non-null name of the Chapter */
            name: string;
            /**
             * Format: int64
             * @description Number of marines in the chapter (must be between 1 and 1000)
             */
            marinesCount: number;
        };
        ChapterWithId: components["schemas"]["Chapter"] & {
            /**
             * Format: int64
             * @description Unique auto-generated ID
             */
            id: number;
        };
        /**
         * @example {
         *       "error": "Invalid weapon types: LASER_CANNON. Valid values: BOLTGUN,HEAVY_BOLTGUN,FLAMER,HEAVY_FLAMER,MULTI_MELTA",
         *       "timestamp": "2025-11-07T14:30:00.000Z"
         *     }
         */
        ErrorResponse: {
            /** @description Human-readable error message */
            error?: string;
            /**
             * Format: date-time
             * @description Timestamp when the error occurred
             */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculateHealthSum: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sum of health values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    calculateHealthAverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Average health value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    filterSpaceMarinesByWeapons: {
        parameters: {
            query: {
                /** @description List of weapon types to filter by (repeat parameter for multiple values) */
                weaponTypes: ("BOLTGUN" | "HEAVY_BOLTGUN" | "FLAMER" | "HEAVY_FLAMER" | "MULTI_MELTA")[];
                /** @description Zero-based page index */
                page?: number;
                /** @description Number of items per page (max 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of filtered Space Marines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSpaceMarineResponse"];
                };
            };
            /** @description Invalid weapon type or pagination parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignMarineToChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the Chapter to assign the marine to */
                chapterId: number;
                /** @description ID of the Space Marine to assign */
                marineId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space Marine successfully assigned to Chapter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMarine"];
                };
            };
            /** @description Invalid IDs provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Chapter or Space Marine not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllSpaceMarines: {
        parameters: {
            query?: {
                /** @description Zero-based page index */
                page?: number;
                /** @description Number of items per page (max 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of Space Marines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSpaceMarineResponse"];
                };
            };
        };
    };
    createSpaceMarine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceMarineCreateRequest"];
            };
        };
        responses: {
            /** @description Space Marine created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMarine"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSpaceMarineById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space Marine found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMarine"];
                };
            };
            /** @description Space Marine not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSpaceMarine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceMarineUpdateRequest"];
            };
        };
        responses: {
            /** @description Space Marine updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceMarine"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Space Marine not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSpaceMarine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space Marine deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Space Marine not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    calculateHealthSumLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sum of health values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    calculateHealthAverageLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Average health value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    getAllCoordinates: {
        parameters: {
            query?: {
                /** @description Zero-based page index */
                page?: number;
                /** @description Number of items per page (max 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of Coordinates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCoordinatesResponse"];
                };
            };
        };
    };
    createCoordinates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coordinates"];
            };
        };
        responses: {
            /** @description Coordinates created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinatesWithId"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCoordinatesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coordinates found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinatesWithId"];
                };
            };
            /** @description Coordinates not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCoordinates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coordinates"];
            };
        };
        responses: {
            /** @description Coordinates updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinatesWithId"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinates not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCoordinates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coordinates deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinates not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllChapters: {
        parameters: {
            query?: {
                /** @description Zero-based page index */
                page?: number;
                /** @description Number of items per page (max 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of Chapters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChapterResponse"];
                };
            };
        };
    };
    createChapter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Chapter"];
            };
        };
        responses: {
            /** @description Chapter created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterWithId"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChapterById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterWithId"];
                };
            };
            /** @description Chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Chapter"];
            };
        };
        responses: {
            /** @description Chapter updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterWithId"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
