/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.shared

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun testApp() {
        assertEquals(4, 2 + 2)
    }
}
